services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DOMAIN=bruno-devic-interview-task-instance-ujvch7.us1.zitadel.cloud
      - KEY_PATH=key.json
      - SERVER_PORT=:8080
      - FRONTEND_URL=http://localhost:3000
